### ISSUE TITLE
Editable fields in Playlist templates do not open when the area in the template is clicked on

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/web-component-rise-playlist#24]
### What is the expected behavior?

When you click on an editable area of a template, the field to edit opens on the left menu

### What is the actual behavior?

When you click on an editable area in the template, nothing happens.

Per Mat: "This doesn’t seem to be limited to this template. Anytime a playlist has content inside it, it doesn’t appear you can click on it to open the editor window."

### What steps can be taken to replicate the problem?

Open the Zoned Flyer template and click an editable area.

**Comment by mmeiers** [comment]
@alex-deaconu @stulees I noticed this happens regardless of what the content you add to a playlist is. So for example an image component that would be otherwise selectable outside of the playlist cannot be selected.
https://apps-stage-0.risevision.com/templates/edit/f3652b19-2240-4c18-b6c2-97d0ee8bcb91/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f 

The use case JR was testing was HTML embed inside playlist so I wanted to make sure it wasn't the behavior of the individual component "HTML Embed" and was playlist.
